### ISSUE TITLE
Building not possible

### ISSUE THREAD

**Issue by abergmeier** [lineage-rpi/android_local_manifest#8] opened 2020-05-06 19:47 UTC
I am trying to find documentation on how to build the Raspberry variant but my Google foo seems to be weak (also I am not familiar with the implicits of _repo_).
So far I tried various permutations of:

```
repo init -u https://github.com/lineage-rpi/android_local_manifest.git -b lineage-16.0 -m manifest_brcm_rpi.xml
```

but failed.
Latest error is:
```
fatal: manifest 'manifest_brcm_rpi.xml' not available
fatal: no remote for project lineage-rpi/android_device_brcm_rpi3 within /lineage-rpi_android_local_manifest/.repo/manifests/manifest_brcm_rpi.xml
```

From the limited knowledge about repo that I have it is really a glorified wrapper around git.
So I would assume that I need to do trigger some magic switch of repo so it sets up remotes!?

**Comment by KonstaT** [comment] 2020-05-07 05:07
There's source code and build instructions for my LineageOS 14.1 & 15.1 builds for Pi 3 (https://github.com/lineage-rpi/android_local_manifest/tree/cm-14.1 & https://github.com/lineage-rpi/android_local_manifest/tree/lineage-15.1, respectively). I haven't released the full device specific source code for my LineageOS 16.0 builds (both Pi 3 & Pi 4) because someone sold builds off of the sources I previously released without complying with open source licensing.

You can use the lineage-16.0 branch to build the kernel, though. E.g. for Pi 4:

```
repo init -u git://github.com/LineageOS/android.git -b lineage-16.0
curl --create-dirs -L -o .repo/local_manifests/manifest_brcm_rpi.xml -O -L https://raw.githubusercontent.com/lineage-rpi/android_local_manifest/lineage-16.0/manifest_brcm_rpi.xml
repo sync
```

```
. build/envsetup.sh
lunch lineage_rpi4-userdebug
mka kernel
```

Also building the kernel standalone is possible so you don't need to download the whole Android source code for this.

Clone kernel source (https://github.com/lineage-rpi/android_kernel_brcm_rpi/tree/lineage-16.0).
Clone proprietaries to get firmware files (https://github.com/lineage-rpi/proprietary_vendor_brcm/tree/lineage-16.0).
Clone AOSP toolchain (https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+/refs/tags/android-9.0.0_r52).

Modify firmware path according to where you've saved them (https://github.com/lineage-rpi/android_kernel_brcm_rpi/blob/lineage-16.0/arch/arm/configs/lineageos_rpi4_defconfig#L1365). Also make note where you've saved the toolchain.

```
ARCH=arm make lineageos_rpi4_defconfig
ARCH=arm CROSS_COMPILE=path/to/arm-linux-androideabi-4.9/bin/arm-linux-androidkernel- make zImage dtbs -jX
```

**Closed as completed by KonstaT** 2020-05-07 05:07 UTC

**Comment by owahltinez** [comment] 2021-05-09 21:18
Hello, I am trying to reproduce the builds for RPI4. Is it still true that you have not released the source code?

**Comment by renhuihhh** [comment] 2023-10-07 16:24
> . build/envsetup.sh
> lunch lineage_rpi4-userdebug
> mka kernel

@KonstaT I have build branch 17.1 for rpi4 and see the colorful rainbow view all the time until I see comment 8,  I followed , however  I got this when mka kernel command on branch 16.0:
`[597/1038] including prebuilts/sdk/Android.mk ...
build/make/core/base_rules.mk:260: error: prebuilts/sdk/tools: MODULE.linux.EXECUTABLES.jack-admin already defined by jack/server/jack-server.
00:15:08 ckati failed with: exit status 1
`
help please, emm  ... I am newcomer for  this

**Comment by KonstaT** [comment] 2023-10-09 08:36
> > . build/envsetup.sh
> > lunch lineage_rpi4-userdebug
> > mka kernel
> 
> @KonstaT I have build branch 17.1 for rpi4 and see the colorful rainbow view all the time until I see comment 8, I followed , however I got this when mka kernel command on branch 16.0: `[597/1038] including prebuilts/sdk/Android.mk ... build/make/core/base_rules.mk:260: error: prebuilts/sdk/tools: MODULE.linux.EXECUTABLES.jack-admin already defined by jack/server/jack-server. 00:15:08 ckati failed with: exit status 1 ` help please, emm ... I am newcomer for this

As mentioned above, there's source code and build instructions for my LineageOS 14.1 & 15.1 builds for Pi 3 (https://github.com/lineage-rpi/android_local_manifest/tree/cm-14.1 & https://github.com/lineage-rpi/android_local_manifest/tree/lineage-15.1, respectively).

`mka kernel` would only build the Linux kernel that you would replace in the boot partition of the existing Android image.

If you want to build AOSP (or something AOSP based such as LineageOS) for Pi 4, you can look into Raspberry Vanilla project.
https://github.com/raspberry-vanilla

**Comment by renhuihhh** [comment] 2023-10-18 16:01
> > > . build/envsetup.sh
> > > lunch lineage_rpi4-userdebug
> > > mka kernel
> > 
> > 
> > @KonstaT I have build branch 17.1 for rpi4 and see the colorful rainbow view all the time until I see comment 8, I followed , however I got this when mka kernel command on branch 16.0: `[597/1038] including prebuilts/sdk/Android.mk ... build/make/core/base_rules.mk:260: error: prebuilts/sdk/tools: MODULE.linux.EXECUTABLES.jack-admin already defined by jack/server/jack-server. 00:15:08 ckati failed with: exit status 1 ` help please, emm ... I am newcomer for this
> 
> As mentioned above, there's source code and build instructions for my LineageOS 14.1 & 15.1 builds for Pi 3 (https://github.com/lineage-rpi/android_local_manifest/tree/cm-14.1 & https://github.com/lineage-rpi/android_local_manifest/tree/lineage-15.1, respectively).
> 
> `mka kernel` would only build the Linux kernel that you would replace in the boot partition of the existing Android image.
> 
> If you want to build AOSP (or something AOSP based such as LineageOS) for Pi 4, you can look into Raspberry Vanilla project. https://github.com/raspberry-vanilla

thanks
